"""Add config tables

Revision ID: 0fac44af5a9c
Revises: 18c6ae18a160
Create Date: 2020-10-17 16:31:53.780683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fac44af5a9c'
down_revision = '18c6ae18a160'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config_message_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_name', sa.String(length=100), nullable=False),
    sa.Column('template', sa.String(length=2000), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('config_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment_karma_flag_threshold', sa.Integer(), nullable=True),
    sa.Column('comment_karma_remove_threshold', sa.Integer(), nullable=True),
    sa.Column('index_api', sa.String(length=150), nullable=True),
    sa.Column('util_api', sa.String(length=150), nullable=True),
    sa.Column('top_post_offer_watch', sa.Boolean(), nullable=True),
    sa.Column('repost_watch_enabled', sa.Boolean(), nullable=True),
    sa.Column('ingest_repost_check_image', sa.Boolean(), nullable=True),
    sa.Column('ingest_repost_check_link', sa.Boolean(), nullable=True),
    sa.Column('ingest_repost_check_text', sa.Boolean(), nullable=True),
    sa.Column('ingest_repost_check_video', sa.Boolean(), nullable=True),
    sa.Column('image_repost_target_image_match', sa.Integer(), nullable=True),
    sa.Column('image_repost_target_image_meme_match', sa.Integer(), nullable=True),
    sa.Column('image_repost_target_annoy_distance', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('config_settings')
    op.drop_table('config_message_templates')
    # ### end Alembic commands ###
