"""notificaiton to monitored sub

Revision ID: 279f1e8d64eb
Revises: 8d3377b141a8
Create Date: 2020-12-16 19:26:14.383264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '279f1e8d64eb'
down_revision = '8d3377b141a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reddit_monitored_sub', sa.Column('activation_notification_sent', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reddit_monitored_sub', 'activation_notification_sent')
    # ### end Alembic commands ###
