"""add template slug

Revision ID: 319d257ae614
Revises: ae154e44a9b8
Create Date: 2020-10-25 22:37:12.362852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '319d257ae614'
down_revision = 'ae154e44a9b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('config_message_templates', sa.Column('template_slug', sa.String(length=100), nullable=False))
    op.create_unique_constraint(None, 'config_message_templates', ['template_slug'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'config_message_templates', type_='unique')
    op.drop_column('config_message_templates', 'template_slug')
    # ### end Alembic commands ###
