"""add proxy table

Revision ID: 31d210ea9abe
Revises: eca6fa2ea7a2
Create Date: 2023-03-10 19:19:35.926649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31d210ea9abe'
down_revision = 'eca6fa2ea7a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('http_proxy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=23), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('cooldown_expire', sa.DateTime(), nullable=True),
    sa.Column('times_used', sa.Integer(), nullable=False),
    sa.Column('successive_failures', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('http_proxy')
    # ### end Alembic commands ###
