"""create author index

Revision ID: 7332736c6ef4
Revises: 700576ba9d88
Create Date: 2020-10-12 19:20:36.418076

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7332736c6ef4'
down_revision = '700576ba9d88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot_stat', sa.Column('comments_left', sa.Integer(), nullable=True))
    op.drop_column('bot_stat', 'comments')
    op.create_index('idx_author', 'image_reposts', ['author'], unique=False)
    op.create_index('idx_author', 'link_reposts', ['author'], unique=False)
    op.create_index('idx_source', 'reddit_image_search', ['source'], unique=False)
    op.drop_index('idx _source', table_name='reddit_image_search')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx _source', 'reddit_image_search', ['source'], unique=False)
    op.drop_index('idx_source', table_name='reddit_image_search')
    op.drop_index('idx_author', table_name='link_reposts')
    op.drop_index('idx_author', table_name='image_reposts')
    op.add_column('bot_stat', sa.Column('comments', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('bot_stat', 'comments_left')
    # ### end Alembic commands ###
