"""image repost index

Revision ID: 77a4e176572e
Revises: ee1c9310194b
Create Date: 2020-10-13 22:08:09.234664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77a4e176572e'
down_revision = 'ee1c9310194b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_repost_of_date', 'image_reposts', ['detected_at', 'author'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_repost_of_date', table_name='image_reposts')
    # ### end Alembic commands ###
