"""change MonitoredSub column names

Revision ID: 8d3377b141a8
Revises: a53c1ffe8f99
Create Date: 2020-12-16 18:32:30.175761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d3377b141a8'
down_revision = 'a53c1ffe8f99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reddit_monitored_sub', sa.Column('failed_admin_check_count', sa.Integer(), nullable=True))
    op.add_column('reddit_monitored_sub', sa.Column('only_comment_on_repost', sa.Boolean(), nullable=True))
    op.add_column('reddit_monitored_sub', sa.Column('report_reposts', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reddit_monitored_sub', 'report_reposts')
    op.drop_column('reddit_monitored_sub', 'only_comment_on_repost')
    op.drop_column('reddit_monitored_sub', 'failed_admin_check_count')
    # ### end Alembic commands ###
