"""edit image index table

Revision ID: 8e501b1ac31c
Revises: 26e2f11e1955
Create Date: 2022-05-15 12:39:26.599598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e501b1ac31c'
down_revision = '26e2f11e1955'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_index_map', sa.Column('reddit_image_post_db_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image_index_map', 'reddit_image_post_db_id')
    # ### end Alembic commands ###
