"""Add config tables

Revision ID: ae154e44a9b8
Revises: 0fac44af5a9c
Create Date: 2020-10-17 16:34:16.328787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae154e44a9b8'
down_revision = '0fac44af5a9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'config_message_templates', ['template_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'config_message_templates', type_='unique')
    # ### end Alembic commands ###
