"""add stats image repost

Revision ID: cfffe117cd7b
Revises: 77a4e176572e
Create Date: 2020-10-14 07:42:26.262883

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cfffe117cd7b'
down_revision = '77a4e176572e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stats_general',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_reposts_detected', sa.Integer(), nullable=True),
    sa.Column('link_reposts_detected', sa.Integer(), nullable=True),
    sa.Column('private_messages_sent', sa.Integer(), nullable=True),
    sa.Column('comments_left', sa.Integer(), nullable=True),
    sa.Column('summons_received', sa.Integer(), nullable=True),
    sa.Column('karma_gained', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stats_top_image_repost',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.String(length=100), nullable=False),
    sa.Column('repost_count', sa.Integer(), nullable=False),
    sa.Column('days', sa.Integer(), nullable=False),
    sa.Column('nsfw', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('bot_stat')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_stat',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('image_reposts_detected', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('link_reposts_detected', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('private_messages_sent', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('summons_received', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('karma_gained', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('comments_left', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('stats_top_image_repost')
    op.drop_table('stats_general')
    # ### end Alembic commands ###
