"""repost modmail to Monitored sub

Revision ID: e7b3e28cbe72
Revises: 7ecb5b67d5c9
Create Date: 2021-01-30 08:35:26.788077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7b3e28cbe72'
down_revision = '7ecb5b67d5c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reddit_monitored_sub', sa.Column('send_repost_modmail', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reddit_monitored_sub', 'send_repost_modmail')
    # ### end Alembic commands ###
