"""add report flag to sub monitor

Revision ID: 00c814a44040
Revises: 88d0c2d9a708
Create Date: 2019-10-20 22:17:13.952301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00c814a44040'
down_revision = '88d0c2d9a708'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reddit_monitored_sub', sa.Column('report_submission', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reddit_monitored_sub', 'report_submission')
    # ### end Alembic commands ###
