"""stats daily count

Revision ID: 012982a4fe39
Revises: 3db890f23d90
Create Date: 2023-08-02 21:44:59.302625

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '012982a4fe39'
down_revision = '3db890f23d90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stat_daily_count', sa.Column('summons_24h', sa.Integer(), nullable=True))
    op.drop_column('stat_daily_count', 'summons_24')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stat_daily_count', sa.Column('summons_24', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('stat_daily_count', 'summons_24h')
    # ### end Alembic commands ###
