"""add imaage URLs to subreddits

Revision ID: 01cdf2a1a340
Revises: 6a43483a407f
Create Date: 2026-01-21 20:55:23.529809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01cdf2a1a340'
down_revision = '6a43483a407f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subreddit', sa.Column('banner_image', sa.String(length=2048), nullable=True))
    op.add_column('subreddit', sa.Column('avatar_image', sa.String(length=2048), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subreddit', 'avatar_image')
    op.drop_column('subreddit', 'banner_image')
    # ### end Alembic commands ###
