"""initial

Revision ID: 025cfeb7cfdd
Revises: 
Create Date: 2019-04-04 21:58:24.172745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '025cfeb7cfdd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reddit_image_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=2000, collation='utf8mb4_general_ci'), nullable=False),
    sa.Column('shortlink', sa.String(length=300), nullable=True),
    sa.Column('perma_link', sa.String(length=1000, collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('author', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(), nullable=True),
    sa.Column('subreddit', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=1000, collation='utf8mb4_general_ci'), nullable=False),
    sa.Column('crosspost_parent', sa.String(length=200), nullable=True),
    sa.Column('dhash_v', sa.String(length=64), nullable=True),
    sa.Column('dhash_h', sa.String(length=64), nullable=True),
    sa.Column('ahash', sa.String(length=64), nullable=True),
    sa.Column('checked_repost', sa.Boolean(), nullable=True),
    sa.Column('last_deleted_check', sa.DateTime(), nullable=True),
    sa.Column('ingested_from', sa.String(length=40), nullable=True),
    sa.Column('bad_url', sa.Boolean(), nullable=True),
    sa.Column('repost_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('reddit_image_post')
    # ### end Alembic commands ###
