"""change meme template

Revision ID: 039ee02ef918
Revises: dd54702aeb24
Create Date: 2020-09-02 13:08:06.367445

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '039ee02ef918'
down_revision = 'dd54702aeb24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meme_template', sa.Column('dhash_256', sa.String(length=256), nullable=True))
    op.add_column('meme_template', sa.Column('post_id', sa.String(length=100), nullable=False))
    op.create_unique_constraint(None, 'meme_template', ['post_id'])
    op.drop_column('meme_template', 'dhash_v')
    op.drop_column('meme_template', 'target_annoy')
    op.drop_column('meme_template', 'target_hamming')
    op.drop_column('meme_template', 'template_detection_hamming')
    op.drop_column('meme_template', 'approved')
    op.drop_column('meme_template', 'created_from_submission')
    op.drop_column('meme_template', 'ahash')
    op.drop_column('meme_template', 'example')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meme_template', sa.Column('example', mysql.VARCHAR(length=500), nullable=True))
    op.add_column('meme_template', sa.Column('ahash', mysql.VARCHAR(length=64), nullable=True))
    op.add_column('meme_template', sa.Column('created_from_submission', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('meme_template', sa.Column('approved', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('meme_template', sa.Column('template_detection_hamming', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('meme_template', sa.Column('target_hamming', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('meme_template', sa.Column('target_annoy', mysql.FLOAT(), nullable=True))
    op.add_column('meme_template', sa.Column('dhash_v', mysql.VARCHAR(length=64), nullable=True))
    op.drop_constraint(None, 'meme_template', type_='unique')
    op.drop_column('meme_template', 'post_id')
    op.drop_column('meme_template', 'dhash_256')
    # ### end Alembic commands ###
