"""subreddit to summons

Revision ID: 05166286768a
Revises: 3d9ff300f784
Create Date: 2023-07-23 19:19:19.042563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05166286768a'
down_revision = '3d9ff300f784'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('summons', sa.Column('subreddit', sa.String(length=25), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('summons', 'subreddit')
    # ### end Alembic commands ###
