"""add banned sub

Revision ID: 0546d6c30c1a
Revises: 1868445ff23e
Create Date: 2020-05-17 22:17:21.269745

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0546d6c30c1a'
down_revision = '1868445ff23e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banned_subreddit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subreddit', sa.String(length=100), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=True),
    sa.Column('last_checked', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subreddit')
    )


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('banned_subreddit')
    # ### end Alembic commands ###
