"""update subreddit table

Revision ID: 06ca90d1031d
Revises: 7cba10c4a9b9
Create Date: 2024-12-14 12:10:45.689071

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '06ca90d1031d'
down_revision = '7cba10c4a9b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subreddit', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('subreddit', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.add_column('subreddit', sa.Column('active_user_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subreddit', 'active_user_count')
    op.drop_column('subreddit', 'deleted')
    op.drop_column('subreddit', 'created_at')
    # ### end Alembic commands ###
