"""fix karma typo

Revision ID: 0842298ca603
Revises: 6400abfc6db9
Create Date: 2019-11-11 20:42:18.513946

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0842298ca603'
down_revision = '6400abfc6db9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reddit_bot_comment', sa.Column('karma', sa.Integer(), nullable=True))
    op.drop_column('reddit_bot_comment', 'karam')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reddit_bot_comment', sa.Column('karam', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('reddit_bot_comment', 'karma')
    # ### end Alembic commands ###
