"""init

Revision ID: 0a37fbda21ef
Revises: 
Create Date: 2022-07-03 15:14:46.037212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a37fbda21ef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banned_subreddit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subreddit', sa.String(length=100), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=True),
    sa.Column('last_checked', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subreddit')
    )
    op.create_table('banned_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('reason', sa.String(length=150), nullable=False),
    sa.Column('banned_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('bot_private_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('body', sa.String(length=1000), nullable=False),
    sa.Column('in_response_to_comment', sa.String(length=20), nullable=True),
    sa.Column('in_response_to_post', sa.String(length=100), nullable=True),
    sa.Column('recipient', sa.String(length=150), nullable=False),
    sa.Column('triggered_from', sa.String(length=50), nullable=False),
    sa.Column('message_sent_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('config_message_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_name', sa.String(length=100), nullable=False),
    sa.Column('template_slug', sa.String(length=100), nullable=False),
    sa.Column('template', sa.String(length=2000), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_name'),
    sa.UniqueConstraint('template_slug')
    )
    op.create_table('meme_hash',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.String(length=6), nullable=False),
    sa.Column('hash', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id')
    )
    op.create_table('monitored_sub',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('repost_only', sa.Boolean(), nullable=True),
    sa.Column('report_submission', sa.Boolean(), nullable=True),
    sa.Column('report_msg', sa.String(length=200), nullable=True),
    sa.Column('requestor', sa.String(length=150), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.Column('target_hamming', sa.Integer(), nullable=True),
    sa.Column('target_annoy', sa.Float(), nullable=True),
    sa.Column('target_days_old', sa.Integer(), nullable=True),
    sa.Column('same_sub_only', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('filter_crossposts', sa.Boolean(), nullable=True),
    sa.Column('filter_same_author', sa.Boolean(), nullable=True),
    sa.Column('sticky_comment', sa.Boolean(), nullable=True),
    sa.Column('remove_repost', sa.Boolean(), nullable=True),
    sa.Column('removal_reason', sa.String(length=200), nullable=True),
    sa.Column('lock_post', sa.Boolean(), nullable=True),
    sa.Column('mark_as_oc', sa.Boolean(), nullable=True),
    sa.Column('repost_response_template', sa.String(length=2000), nullable=True),
    sa.Column('oc_response_template', sa.String(length=2000), nullable=True),
    sa.Column('meme_filter', sa.Boolean(), nullable=True),
    sa.Column('title_ignore_keywords', sa.String(length=200), nullable=True),
    sa.Column('disable_summons_after_auto_response', sa.Boolean(), nullable=True),
    sa.Column('disable_bot_summons', sa.Boolean(), nullable=True),
    sa.Column('only_allow_one_summons', sa.Boolean(), nullable=True),
    sa.Column('remove_additional_summons', sa.Boolean(), nullable=True),
    sa.Column('check_all_submissions', sa.Boolean(), nullable=True),
    sa.Column('check_title_similarity', sa.Boolean(), nullable=True),
    sa.Column('target_title_match', sa.Integer(), nullable=True),
    sa.Column('subscribers', sa.Integer(), nullable=True),
    sa.Column('is_mod', sa.Boolean(), nullable=True),
    sa.Column('post_permission', sa.Boolean(), nullable=True),
    sa.Column('wiki_permission', sa.Boolean(), nullable=True),
    sa.Column('wiki_managed', sa.Boolean(), nullable=True),
    sa.Column('check_image_posts', sa.Boolean(), nullable=True),
    sa.Column('check_link_posts', sa.Boolean(), nullable=True),
    sa.Column('check_text_posts', sa.Boolean(), nullable=True),
    sa.Column('check_video_posts', sa.Boolean(), nullable=True),
    sa.Column('target_image_match', sa.Integer(), nullable=True),
    sa.Column('target_image_meme_match', sa.Integer(), nullable=True),
    sa.Column('meme_filter_check_text', sa.Boolean(), nullable=True),
    sa.Column('meme_filter_text_target_match', sa.Integer(), nullable=True),
    sa.Column('only_comment_on_repost', sa.Boolean(), nullable=True),
    sa.Column('report_reposts', sa.Boolean(), nullable=True),
    sa.Column('failed_admin_check_count', sa.Integer(), nullable=True),
    sa.Column('activation_notification_sent', sa.Boolean(), nullable=True),
    sa.Column('comment_on_repost', sa.Boolean(), nullable=True),
    sa.Column('comment_on_oc', sa.Boolean(), nullable=True),
    sa.Column('lock_response_comment', sa.Boolean(), nullable=True),
    sa.Column('filter_removed_matches', sa.Boolean(), nullable=True),
    sa.Column('send_repost_modmail', sa.Boolean(), nullable=True),
    sa.Column('nsfw', sa.Boolean(), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.String(length=6), nullable=False),
    sa.Column('url', sa.String(length=2000, collation='utf8mb4_general_ci'), nullable=False),
    sa.Column('shortlink', sa.String(length=300), nullable=True),
    sa.Column('perma_link', sa.String(length=1000, collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('post_type', sa.String(length=20), nullable=True),
    sa.Column('author', sa.String(length=100), nullable=False),
    sa.Column('selftext', sa.Text(length=75000, collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(), nullable=True),
    sa.Column('subreddit', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=1000, collation='utf8mb4_general_ci'), nullable=False),
    sa.Column('crosspost_parent', sa.String(length=200), nullable=True),
    sa.Column('dhash_h', sa.String(length=64), nullable=True),
    sa.Column('last_deleted_check', sa.DateTime(), nullable=True),
    sa.Column('url_hash', sa.String(length=32), nullable=True),
    sa.Column('hash_1', sa.String(length=64), nullable=True),
    sa.Column('hash_2', sa.String(length=64), nullable=True),
    sa.Column('hash_3', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id')
    )
    op.create_index('idx_image_posts', 'post', ['post_type', 'created_at'], unique=False)
    op.create_index('idx_ingest_graph', 'post', ['ingested_at', 'post_type'], unique=False)
    op.create_index('idx_last_delete_check', 'post', ['last_deleted_check', 'post_type'], unique=False)
    op.create_index('idx_url_hash', 'post', ['url_hash'], unique=False)
    op.create_table('site_admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=100), nullable=False),
    sa.Column('super_user', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user')
    )
    op.create_table('bot_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('comment_body', sa.String(length=2000, collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('perma_link', sa.String(length=1000, collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('comment_left_at', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('comment_id', sa.String(length=20), nullable=False),
    sa.Column('karma', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('needs_review', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bot_summons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('requestor', sa.String(length=100), nullable=True),
    sa.Column('comment_id', sa.String(length=100), nullable=True),
    sa.Column('comment_body', sa.String(length=1000, collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('comment_reply', sa.String(length=5000), nullable=True),
    sa.Column('comment_reply_id', sa.String(length=100), nullable=True),
    sa.Column('summons_received_at', sa.DateTime(), nullable=True),
    sa.Column('summons_replied_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('comment_id')
    )
    op.create_index('user_summons_check', 'bot_summons', ['requestor', 'summons_received_at'], unique=False)
    op.create_table('image_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('dhash_h', sa.String(length=64), nullable=True),
    sa.Column('dhash_v', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('create_at_index', 'image_post', ['created_at'], unique=False)
    op.create_table('investigate_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('matches', sa.Integer(), nullable=True),
    sa.Column('found_at', sa.DateTime(), nullable=True),
    sa.Column('url', sa.String(length=2000, collation='utf8mb4_general_ci'), nullable=False),
    sa.Column('flag_reason', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meme_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dhash_h', sa.String(length=64), nullable=True),
    sa.Column('dhash_256', sa.String(length=256), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meme_template_potential',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('submitted_by', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('vote_total', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monitored_sub_checked',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('checked_at', sa.DateTime(), nullable=True),
    sa.Column('monitored_sub_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['monitored_sub_id'], ['monitored_sub.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monitored_sub_config_change',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=100), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=True),
    sa.Column('config_key', sa.String(length=100), nullable=False),
    sa.Column('old_value', sa.String(length=2000), nullable=True),
    sa.Column('new_value', sa.String(length=2000), nullable=True),
    sa.Column('monitored_sub_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['monitored_sub_id'], ['monitored_sub.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_subreddit', 'monitored_sub_config_change', ['monitored_sub_id', 'updated_at'], unique=False)
    op.create_table('monitored_sub_config_revision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('revision_id', sa.String(length=36), nullable=False),
    sa.Column('revised_by', sa.String(length=100), nullable=False),
    sa.Column('config', sa.String(length=1000), nullable=False),
    sa.Column('config_loaded_at', sa.DateTime(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.Column('notified', sa.Boolean(), nullable=True),
    sa.Column('monitored_sub_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['monitored_sub_id'], ['monitored_sub.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('revision_id')
    )
    op.create_table('post_hash',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url_hash', sa.String(length=32), nullable=True),
    sa.Column('hash_1', sa.String(length=64), nullable=True),
    sa.Column('hash_2', sa.String(length=64), nullable=True),
    sa.Column('hash_3', sa.String(length=64), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repost_search',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('search_params', sa.String(length=1000), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repost_watch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('user', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_detection', sa.DateTime(), nullable=True),
    sa.Column('same_sub', sa.Boolean(), nullable=False),
    sa.Column('expire_after', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('reported_by', sa.String(length=100), nullable=False),
    sa.Column('post_type', sa.String(length=15), nullable=True),
    sa.Column('report_type', sa.String(length=25), nullable=False),
    sa.Column('meme_template', sa.Integer(), nullable=True),
    sa.Column('reported_at', sa.DateTime(), nullable=True),
    sa.Column('msg_body', sa.String(length=1000), nullable=True),
    sa.Column('message_id', sa.String(length=20), nullable=False),
    sa.Column('sent_for_voting', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('image_index_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('annoy_index_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('image_post_id', sa.Integer(), nullable=True),
    sa.Column('index_name', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['image_post_id'], ['image_post.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('id_map', 'image_index_map', ['annoy_index_id', 'index_name'], unique=False)
    op.create_table('meme_template_potential_votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('meme_template_potential_id', sa.Integer(), nullable=True),
    sa.Column('user', sa.String(length=100), nullable=False),
    sa.Column('vote', sa.Integer(), nullable=False),
    sa.Column('voted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['meme_template_potential_id'], ['meme_template_potential.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repost',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('repost_of_id', sa.Integer(), nullable=True),
    sa.Column('search_id', sa.Integer(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['repost_of_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['search_id'], ['repost_search.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('repost')
    op.drop_table('meme_template_potential_votes')
    op.drop_index('id_map', table_name='image_index_map')
    op.drop_table('image_index_map')
    op.drop_table('user_report')
    op.drop_table('repost_watch')
    op.drop_table('repost_search')
    op.drop_table('post_hash')
    op.drop_table('monitored_sub_config_revision')
    op.drop_index('idx_subreddit', table_name='monitored_sub_config_change')
    op.drop_table('monitored_sub_config_change')
    op.drop_table('monitored_sub_checked')
    op.drop_table('meme_template_potential')
    op.drop_table('meme_template')
    op.drop_table('investigate_post')
    op.drop_index('create_at_index', table_name='image_post')
    op.drop_table('image_post')
    op.drop_index('user_summons_check', table_name='bot_summons')
    op.drop_table('bot_summons')
    op.drop_table('bot_comment')
    op.drop_table('site_admin')
    op.drop_index('idx_url_hash', table_name='post')
    op.drop_index('idx_last_delete_check', table_name='post')
    op.drop_index('idx_ingest_graph', table_name='post')
    op.drop_index('idx_image_posts', table_name='post')
    op.drop_table('post')
    op.drop_table('monitored_sub')
    op.drop_table('meme_hash')
    op.drop_table('config_message_templates')
    op.drop_table('bot_private_message')
    op.drop_table('banned_users')
    op.drop_table('banned_subreddit')
    # ### end Alembic commands ###
