"""added is_private

Revision ID: 150fe2b02cd6
Revises: 06ca90d1031d
Create Date: 2024-12-14 12:34:31.990041

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '150fe2b02cd6'
down_revision = '06ca90d1031d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subreddit', sa.Column('is_private', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subreddit', 'is_private')
    # ### end Alembic commands ###
