"""Add requestor to summons

Revision ID: 172ec96586e4
Revises: 54ca08cc77e6
Create Date: 2019-02-17 22:13:35.830856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '172ec96586e4'
down_revision = '54ca08cc77e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reddit_bot_summons', sa.Column('requestor', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reddit_bot_summons', 'requestor')
    # ### end Alembic commands ###
