"""add new image post

Revision ID: 183f811bafe5
Revises: 440d2104cb6f
Create Date: 2019-08-25 08:23:14.287225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '183f811bafe5'
down_revision = '440d2104cb6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reddit_image_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.String(length=100), nullable=False),
    sa.Column('dhash_v', sa.String(length=64), nullable=True),
    sa.Column('dhash_h', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reddit_image_post')
    # ### end Alembic commands ###
