"""0.1.7

Revision ID: 1868445ff23e
Revises: a42b666cd001
Create Date: 2020-05-16 17:38:26.888818

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1868445ff23e'
down_revision = 'a42b666cd001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('reddit_monitored_sub', sa.Column('removal_reason', sa.String(length=200), nullable=True))
    op.drop_column('reddit_monitored_sub', 'removal_reason_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('reddit_monitored_sub', sa.Column('removal_reason_id', mysql.VARCHAR(length=20), nullable=True))
    op.drop_column('reddit_monitored_sub', 'removal_reason')

    # ### end Alembic commands ###
