"""index to link repost

Revision ID: 18c6ae18a160
Revises: cfffe117cd7b
Create Date: 2020-10-14 11:06:58.799449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18c6ae18a160'
down_revision = 'cfffe117cd7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_repost_of_date', 'link_reposts', ['detected_at', 'author'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_repost_of_date', table_name='link_reposts')
    # ### end Alembic commands ###
