"""crosspost and author filter

Revision ID: 1afc8ef03612
Revises: f61cc594a453
Create Date: 2020-06-17 07:38:55.696870

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1afc8ef03612'
down_revision = 'f61cc594a453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('reddit_monitored_sub', sa.Column('filter_crossposts', sa.Boolean(), nullable=True))
    op.add_column('reddit_monitored_sub', sa.Column('filter_same_author', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('reddit_monitored_sub', 'filter_same_author')
    op.drop_column('reddit_monitored_sub', 'filter_crossposts')

    # ### end Alembic commands ###
