"""stats daily count

Revision ID: 1c39dac72a48
Revises: 6e1ac9f20f6e
Create Date: 2023-08-02 21:39:55.162332

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1c39dac72a48'
down_revision = '6e1ac9f20f6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_check',
    sa.Column('username', sa.String(length=25), nullable=False),
    sa.Column('onlyfans_links', sa.Boolean(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('last_checked', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('username'),
    sa.UniqueConstraint('username')
    )
    op.create_index('idx_last_checked', 'user_check', ['last_checked'], unique=False)
    op.add_column('stat_daily_count', sa.Column('summons_total', sa.Integer(), nullable=True))
    op.add_column('stat_daily_count', sa.Column('summons_24', sa.Integer(), nullable=True))
    op.add_column('stat_daily_count', sa.Column('comments_total', sa.Integer(), nullable=True))
    op.add_column('stat_daily_count', sa.Column('comments_24h', sa.Integer(), nullable=True))
    op.add_column('stat_daily_count', sa.Column('image_reposts_total', sa.Integer(), nullable=True))
    op.add_column('stat_daily_count', sa.Column('image_reposts_24h', sa.Integer(), nullable=True))
    op.add_column('stat_daily_count', sa.Column('link_reposts_24h', sa.Integer(), nullable=True))
    op.add_column('stat_daily_count', sa.Column('video_reposts_24h', sa.Integer(), nullable=True))
    op.add_column('stat_daily_count', sa.Column('text_reposts_24h', sa.Integer(), nullable=True))
    op.add_column('stat_daily_count', sa.Column('monitored_subreddit_count', sa.Integer(), nullable=True))
    op.drop_column('stat_daily_count', 'summons')
    op.drop_column('stat_daily_count', 'comments')
    op.drop_column('stat_daily_count', 'comment_karma')
    op.drop_column('stat_daily_count', 'image_reposts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stat_daily_count', sa.Column('image_reposts', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('stat_daily_count', sa.Column('comment_karma', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('stat_daily_count', sa.Column('comments', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('stat_daily_count', sa.Column('summons', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('stat_daily_count', 'monitored_subreddit_count')
    op.drop_column('stat_daily_count', 'text_reposts_24h')
    op.drop_column('stat_daily_count', 'video_reposts_24h')
    op.drop_column('stat_daily_count', 'link_reposts_24h')
    op.drop_column('stat_daily_count', 'image_reposts_24h')
    op.drop_column('stat_daily_count', 'image_reposts_total')
    op.drop_column('stat_daily_count', 'comments_24h')
    op.drop_column('stat_daily_count', 'comments_total')
    op.drop_column('stat_daily_count', 'summons_24')
    op.drop_column('stat_daily_count', 'summons_total')
    op.drop_index('idx_last_checked', table_name='user_check')
    op.drop_table('user_check')
    # ### end Alembic commands ###
