"""new hash columns2

Revision ID: 1f7d94d90721
Revises: 9145e32428b4
Create Date: 2019-02-13 12:52:05.948494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f7d94d90721'
down_revision = '9145e32428b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reddit_post', sa.Column('ahash', sa.String(length=64), nullable=True))
    op.add_column('reddit_post', sa.Column('ahash_set_bits', sa.Integer(), nullable=True))
    op.add_column('reddit_post', sa.Column('dhash_h', sa.String(length=64), nullable=True))
    op.add_column('reddit_post', sa.Column('dhash_h_set_bits', sa.Integer(), nullable=True))
    op.add_column('reddit_post', sa.Column('dhash_v', sa.String(length=64), nullable=True))
    op.add_column('reddit_post', sa.Column('dhash_v_set_bits', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reddit_post', 'dhash_v_set_bits')
    op.drop_column('reddit_post', 'dhash_v')
    op.drop_column('reddit_post', 'dhash_h_set_bits')
    op.drop_column('reddit_post', 'dhash_h')
    op.drop_column('reddit_post', 'ahash_set_bits')
    op.drop_column('reddit_post', 'ahash')
    # ### end Alembic commands ###
