"""add URL

Revision ID: 22d0da7bc418
Revises: 840f89301827
Create Date: 2019-11-05 09:33:18.683746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22d0da7bc418'
down_revision = '840f89301827'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('investigate_post', sa.Column('url', sa.String(length=2000, collation='utf8mb4_general_ci'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('investigate_post', 'url')
    # ### end Alembic commands ###
