"""date column change2

Revision ID: 23cfd03f5b32
Revises: d40f77ce5bd7
Create Date: 2023-07-27 20:23:20.352219

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '23cfd03f5b32'
down_revision = 'd40f77ce5bd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stat_daily_count', sa.Column('ran_at', sa.DateTime(), nullable=True))
    op.drop_column('stat_daily_count', 'run_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stat_daily_count', sa.Column('run_at', mysql.DATETIME(), nullable=True))
    op.drop_column('stat_daily_count', 'ran_at')
    # ### end Alembic commands ###
