"""add permissions columns to monitoredsub

Revision ID: 24f60f33e2ea
Revises: cc31bb26980f
Create Date: 2020-04-28 22:08:03.964531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24f60f33e2ea'
down_revision = 'cc31bb26980f'
branch_labels = None
depends_on = None


def upgrade():

    op.add_column('reddit_monitored_sub', sa.Column('is_mod', sa.Boolean(), nullable=True))
    op.add_column('reddit_monitored_sub', sa.Column('post_permission', sa.Boolean(), nullable=True))
    op.add_column('reddit_monitored_sub', sa.Column('wiki_permission', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reddit_monitored_sub', 'wiki_permission')
    op.drop_column('reddit_monitored_sub', 'post_permission')
    op.drop_column('reddit_monitored_sub', 'is_mod')

    # ### end Alembic commands ###
