"""add user review columns

Revision ID: 2565f1890052
Revises: f134f5fecea4
Create Date: 2023-08-06 17:22:44.295387

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2565f1890052'
down_revision = 'f134f5fecea4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_review', sa.Column('content_links_found', sa.Boolean(), nullable=True))
    op.drop_column('user_review', 'fansly_links_found')
    op.drop_column('user_review', 'onlyfans_links_found')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_review', sa.Column('onlyfans_links_found', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('user_review', sa.Column('fansly_links_found', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('user_review', 'content_links_found')
    # ### end Alembic commands ###
