"""update private message table

Revision ID: 25b5025a5875
Revises: 2a338f2d5019
Create Date: 2020-07-26 19:21:27.281859

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '25b5025a5875'
down_revision = '2a338f2d5019'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('reddit_bot_private_message', sa.Column('in_response_to_post', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reddit_bot_private_message', 'in_response_to_post')

    # ### end Alembic commands ###
