"""add offset to finger print

Revision ID: 26f37a5dfadd
Revises: a7b146e14308
Create Date: 2019-03-20 22:25:30.311493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26f37a5dfadd'
down_revision = 'a7b146e14308'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audio_fingerprints', sa.Column('offset', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('audio_fingerprints', 'offset')
    # ### end Alembic commands ###
