"""add private message table

Revision ID: 2a338f2d5019
Revises: 1afc8ef03612
Create Date: 2020-07-26 19:09:06.692969

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2a338f2d5019'
down_revision = '1afc8ef03612'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reddit_bot_private_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('body', sa.String(length=1000), nullable=False),
    sa.Column('in_response_to_comment', sa.String(length=20), nullable=True),
    sa.Column('recipient', sa.String(length=150), nullable=False),
    sa.Column('triggered_from', sa.String(length=50), nullable=False),
    sa.Column('message_sent_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('reddit_bot_private_message')
    # ### end Alembic commands ###
