"""unique link repost post id

Revision ID: 31fee8b62426
Revises: 615326524a9d
Create Date: 2019-03-01 07:49:46.517140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31fee8b62426'
down_revision = '615326524a9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'link_reposts', ['post_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_constraint(None, 'link_reposts', type_='unique')
    # ### end Alembic commands ###
