"""new fields on moinotred sub

Revision ID: 32bcf6ee2dee
Revises: eb7b869ceef6
Create Date: 2019-10-23 08:19:02.786177

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '32bcf6ee2dee'
down_revision = 'eb7b869ceef6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meme_template', 'template_detection_hamming',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.add_column('reddit_monitored_sub', sa.Column('notes', sa.String(length=500), nullable=True))
    op.add_column('reddit_monitored_sub', sa.Column('same_sub_only', sa.Boolean(), nullable=True))
    op.add_column('reddit_monitored_sub', sa.Column('target_days_old', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('reddit_monitored_sub', 'target_days_old')
    op.drop_column('reddit_monitored_sub', 'same_sub_only')
    op.drop_column('reddit_monitored_sub', 'notes')
    op.alter_column('meme_template', 'template_detection_hamming',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###
