"""update top reposts

Revision ID: 32e8590c8f5c
Revises: fcb87257c621
Create Date: 2023-08-02 18:50:22.722374

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '32e8590c8f5c'
down_revision = 'fcb87257c621'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stat_top_repost', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('stat_top_repost', sa.Column('post_id', sa.Integer(), nullable=True))
    op.add_column('stat_top_repost', sa.Column('post_type_id', mysql.TINYINT(), nullable=True))
    op.add_column('stat_top_repost', sa.Column('day_range', sa.Integer(), nullable=True))
    op.drop_index('idx_post_type', table_name='stat_top_repost')
    op.create_index('idx_post_type', 'stat_top_repost', ['post_type_id', 'day_range', 'nsfw'], unique=False)
    op.create_foreign_key(None, 'stat_top_repost', 'post', ['post_id'], ['id'])
    op.create_foreign_key(None, 'stat_top_repost', 'post_type', ['post_type_id'], ['id'])
    op.drop_column('stat_top_repost', 'days')
    op.drop_column('stat_top_repost', 'day_count_7')
    op.drop_column('stat_top_repost', 'post_type')
    op.drop_column('stat_top_repost', 'post_reddit_id')
    op.drop_column('stat_top_repost', 'post_db_id')
    op.drop_column('stat_top_repost', 'total_count')
    op.drop_column('stat_top_repost', 'day_count_1')
    op.drop_column('stat_top_repost', 'day_count_365')
    op.drop_column('stat_top_repost', 'day_count_30')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stat_top_repost', sa.Column('day_count_30', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('stat_top_repost', sa.Column('day_count_365', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('stat_top_repost', sa.Column('day_count_1', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('stat_top_repost', sa.Column('total_count', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('stat_top_repost', sa.Column('post_db_id', mysql.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('stat_top_repost', sa.Column('post_reddit_id', mysql.VARCHAR(length=6), nullable=False))
    op.add_column('stat_top_repost', sa.Column('post_type', mysql.TINYINT(), autoincrement=False, nullable=True))
    op.add_column('stat_top_repost', sa.Column('day_count_7', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('stat_top_repost', sa.Column('days', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'stat_top_repost', type_='foreignkey')
    op.drop_constraint(None, 'stat_top_repost', type_='foreignkey')
    op.drop_index('idx_post_type', table_name='stat_top_repost')
    op.create_index('idx_post_type', 'stat_top_repost', ['post_type', 'nsfw'], unique=False)
    op.drop_column('stat_top_repost', 'day_range')
    op.drop_column('stat_top_repost', 'post_type_id')
    op.drop_column('stat_top_repost', 'post_id')
    op.drop_column('stat_top_repost', 'id')
    # ### end Alembic commands ###
