"""Add cross_post_checked

Revision ID: 3a1c68487eea
Revises: aa64cf52096c
Create Date: 2019-02-02 14:44:14.225677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a1c68487eea'
down_revision = 'aa64cf52096c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reddit_post', sa.Column('cross_post_checked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reddit_post', 'cross_post_checked')
    # ### end Alembic commands ###
