"""add of columsn

Revision ID: 3a38b265323c
Revises: 469dd7ed14df
Create Date: 2023-09-01 10:08:07.529555

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3a38b265323c'
down_revision = '469dd7ed14df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monitored_sub', sa.Column('adult_promoter_remove_post', sa.Boolean(), nullable=True))
    op.add_column('monitored_sub', sa.Column('adult_promoter_ban_user', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monitored_sub', 'adult_promoter_ban_user')
    op.drop_column('monitored_sub', 'adult_promoter_remove_post')
    # ### end Alembic commands ###
