"""fields in submonitor

Revision ID: 3b74da7fd47f
Revises: 7bd7f8d45d36
Create Date: 2020-03-14 08:18:50.493858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b74da7fd47f'
down_revision = '7bd7f8d45d36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('reddit_monitored_sub', sa.Column('lock_post', sa.Boolean(), nullable=True))
    op.add_column('reddit_monitored_sub', sa.Column('mark_as_oc', sa.Boolean(), nullable=True))
    op.add_column('reddit_monitored_sub', sa.Column('removal_reason_id', sa.Integer(), nullable=True))
    op.add_column('reddit_monitored_sub', sa.Column('remove_repost', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reddit_monitored_sub', 'remove_repost')
    op.drop_column('reddit_monitored_sub', 'removal_reason_id')
    op.drop_column('reddit_monitored_sub', 'mark_as_oc')
    op.drop_column('reddit_monitored_sub', 'lock_post')
    # ### end Alembic commands ###
