"""Add enabled col to repostwatch

Revision ID: 3c06d1d8e256
Revises: ee0a870da42b
Create Date: 2019-12-03 08:32:53.139632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c06d1d8e256'
down_revision = 'ee0a870da42b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reddit_repost_watch', sa.Column('enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reddit_repost_watch', 'enabled')

    # ### end Alembic commands ###
