"""author to reposts

Revision ID: 3c5d92bafc35
Revises: 24f60f33e2ea
Create Date: 2020-05-03 19:25:24.292305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c5d92bafc35'
down_revision = '24f60f33e2ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_reposts', sa.Column('author', sa.String(length=100), nullable=False))
    op.add_column('link_reposts', sa.Column('author', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('link_reposts', 'author')
    op.drop_column('image_reposts', 'author')
    # ### end Alembic commands ###
