"""add subreddit to bot_comment

Revision ID: 3d9ff300f784
Revises: c483b833921b
Create Date: 2023-07-20 18:26:09.926615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d9ff300f784'
down_revision = 'c483b833921b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot_comment', sa.Column('subreddit', sa.String(length=25), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bot_comment', 'subreddit')
    # ### end Alembic commands ###
