"""stats daily count

Revision ID: 3db890f23d90
Revises: 1c39dac72a48
Create Date: 2023-08-02 21:42:24.880860

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3db890f23d90'
down_revision = '1c39dac72a48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stat_daily_count', sa.Column('link_reposts_total', sa.Integer(), nullable=True))
    op.add_column('stat_daily_count', sa.Column('video_reposts_total', sa.Integer(), nullable=True))
    op.add_column('stat_daily_count', sa.Column('text_reposts_total', sa.Integer(), nullable=True))
    op.drop_column('stat_daily_count', 'link_reposts')
    op.drop_column('stat_daily_count', 'text_reposts')
    op.drop_column('stat_daily_count', 'video_reposts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stat_daily_count', sa.Column('video_reposts', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('stat_daily_count', sa.Column('text_reposts', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('stat_daily_count', sa.Column('link_reposts', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('stat_daily_count', 'text_reposts_total')
    op.drop_column('stat_daily_count', 'video_reposts_total')
    op.drop_column('stat_daily_count', 'link_reposts_total')
    # ### end Alembic commands ###
