"""Add custom response templates

Revision ID: 3efb6c97a536
Revises: 0a3bf748aa82
Create Date: 2019-11-02 10:48:32.163364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3efb6c97a536'
down_revision = '0a3bf748aa82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reddit_monitored_sub', sa.Column('oc_response_template', sa.String(length=2000), nullable=True))
    op.add_column('reddit_monitored_sub', sa.Column('repost_response_template', sa.String(length=2000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reddit_monitored_sub', 'repost_response_template')
    op.drop_column('reddit_monitored_sub', 'oc_response_template')
    # ### end Alembic commands ###
