"""image hash

Revision ID: 433b9dd1d483
Revises: 9765922e4a38
Create Date: 2019-01-28 08:08:44.026410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '433b9dd1d483'
down_revision = '9765922e4a38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reddit_post', sa.Column('image_hash', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reddit_post', 'image_hash')
    # ### end Alembic commands ###
