"""remove image post

Revision ID: 440d2104cb6f
Revises: 025cfeb7cfdd
Create Date: 2019-08-25 08:19:03.110345

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '440d2104cb6f'
down_revision = '025cfeb7cfdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('post_id', table_name='reddit_image_post')
    op.drop_table('reddit_image_post')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('reddit_image_post',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('post_id', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('url', mysql.VARCHAR(charset='utf8mb4', length=2000), nullable=False),
    sa.Column('shortlink', mysql.VARCHAR(length=300), nullable=True),
    sa.Column('perma_link', mysql.VARCHAR(charset='utf8mb4', length=1000), nullable=True),
    sa.Column('author', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('ingested_at', mysql.DATETIME(), nullable=True),
    sa.Column('subreddit', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('title', mysql.VARCHAR(charset='utf8mb4', length=1000), nullable=False),
    sa.Column('crosspost_parent', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('dhash_v', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('dhash_h', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('ahash', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('checked_repost', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('last_deleted_check', mysql.DATETIME(), nullable=True),
    sa.Column('ingested_from', mysql.VARCHAR(length=40), nullable=True),
    sa.Column('bad_url', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('repost_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB',
    mysql_row_format='COMPRESSED'
    )
    op.create_index('post_id', 'reddit_image_post', ['post_id'], unique=True)
    # ### end Alembic commands ###
