"""add text distance to ms

Revision ID: 469dd7ed14df
Revises: 2565f1890052
Create Date: 2023-08-31 13:52:37.937548

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '469dd7ed14df'
down_revision = '2565f1890052'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monitored_sub', sa.Column('target_text_distance', sa.Float(), nullable=True))
    op.drop_column('monitored_sub', 'meme_filter_text_target_match')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monitored_sub', sa.Column('meme_filter_text_target_match', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('monitored_sub', 'target_text_distance')
    # ### end Alembic commands ###
