"""change repost stat table2

Revision ID: 482b71961424
Revises: 9557a20ecc84
Create Date: 2023-07-31 19:37:25.522140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '482b71961424'
down_revision = '9557a20ecc84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stat_top_reposters', sa.Column('repost_count', sa.Integer(), nullable=False))
    op.add_column('stat_top_reposters', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stat_top_reposters', 'updated_at')
    op.drop_column('stat_top_reposters', 'repost_count')
    # ### end Alembic commands ###
