"""Short Link

Revision ID: 4b8ff067affa
Revises: 3cb433829c56
Create Date: 2019-02-17 17:17:47.139582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b8ff067affa'
down_revision = '3cb433829c56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link_reposts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.String(length=100), nullable=False),
    sa.Column('repost_of', sa.String(length=100), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('reddit_post', sa.Column('short_url', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reddit_post', 'short_url')
    op.drop_table('link_reposts')
    # ### end Alembic commands ###
