"""add image post current

Revision ID: 4ca1d09343bd
Revises: cd82a74af6b8
Create Date: 2019-11-10 08:27:31.684003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ca1d09343bd'
down_revision = 'cd82a74af6b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reddit_image_post_current',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('post_id', sa.String(length=100), nullable=False),
    sa.Column('dhash_v', sa.String(length=64), nullable=True),
    sa.Column('dhash_h', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reddit_image_post_current')
    # ### end Alembic commands ###
