"""add flag reason to investigate

Revision ID: 4de64fd52e67
Revises: 4ca1d09343bd
Create Date: 2019-11-10 18:18:22.941871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4de64fd52e67'
down_revision = '4ca1d09343bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('investigate_post', sa.Column('flag_reason', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('investigate_post', 'flag_reason')
    # ### end Alembic commands ###
