"""update top reposts

Revision ID: 4eb9a001f113
Revises: 32e8590c8f5c
Create Date: 2023-08-02 19:11:25.622118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4eb9a001f113'
down_revision = '32e8590c8f5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stat_top_repost', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stat_top_repost', 'updated_at')
    # ### end Alembic commands ###
