"""add karma and active to botcomment

Revision ID: 4f4476b92ea2
Revises: d92fc4c9f706
Create Date: 2019-11-11 20:15:49.928562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f4476b92ea2'
down_revision = 'd92fc4c9f706'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reddit_bot_comment', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('reddit_bot_comment', sa.Column('karam', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reddit_bot_comment', 'karam')
    op.drop_column('reddit_bot_comment', 'active')
    # ### end Alembic commands ###
