"""edit post search

Revision ID: 4f75d037e368
Revises: 12cf142f86c5
Create Date: 2023-07-09 20:36:15.927381

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4f75d037e368'
down_revision = '12cf142f86c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repost_search', sa.Column('post_type_id', mysql.TINYINT(), nullable=True))
    op.create_index('idx_post_type_searched_at', 'repost_search', ['post_type_id', 'searched_at'], unique=False)
    op.drop_column('repost_search', 'post_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repost_search', sa.Column('post_type', mysql.TINYINT(), autoincrement=False, nullable=True))
    op.drop_index('idx_post_type_searched_at', table_name='repost_search')
    op.drop_column('repost_search', 'post_type_id')
    # ### end Alembic commands ###
