"""voting column in report

Revision ID: 5111c30c2895
Revises: 126af4529c2d
Create Date: 2020-11-11 21:48:11.094851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5111c30c2895'
down_revision = '126af4529c2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reddit_user_report', sa.Column('sent_for_voting', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reddit_user_report', 'sent_for_voting')
    # ### end Alembic commands ###
