"""Rename shortlink

Revision ID: 54ca08cc77e6
Revises: 4b8ff067affa
Create Date: 2019-02-17 21:25:00.897825

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '54ca08cc77e6'
down_revision = '4b8ff067affa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reddit_post', sa.Column('shortlink', sa.String(length=300), nullable=True))
    op.drop_column('reddit_post', 'short_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reddit_post', sa.Column('short_url', mysql.VARCHAR(length=300), nullable=True))
    op.drop_column('reddit_post', 'shortlink')
    # ### end Alembic commands ###
