"""add user review

Revision ID: 550b48e2c922
Revises: 012982a4fe39
Create Date: 2023-08-05 09:36:49.243458

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '550b48e2c922'
down_revision = '012982a4fe39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_review',
    sa.Column('username', sa.String(length=25), nullable=False),
    sa.Column('onlyfans_detected', sa.Boolean(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('last_checked', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('username'),
    sa.UniqueConstraint('username')
    )
    op.create_index('idx_last_checked', 'user_review', ['last_checked'], unique=False)
    op.drop_index('idx_last_checked', table_name='user_check')
    op.drop_index('username', table_name='user_check')
    op.drop_table('user_check')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_check',
    sa.Column('username', mysql.VARCHAR(length=25), nullable=False),
    sa.Column('onlyfans_links', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('added_at', mysql.DATETIME(), nullable=False),
    sa.Column('last_checked', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('username'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('username', 'user_check', ['username'], unique=False)
    op.create_index('idx_last_checked', 'user_check', ['last_checked'], unique=False)
    op.drop_index('idx_last_checked', table_name='user_review')
    op.drop_table('user_review')
    # ### end Alembic commands ###
