"""drop unqiue index

Revision ID: 56a227d5ad00
Revises: 26f37a5dfadd
Create Date: 2019-03-20 22:30:05.517877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56a227d5ad00'
down_revision = '26f37a5dfadd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('post_id', table_name='audio_fingerprints')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('post_id', 'audio_fingerprints', ['post_id'], unique=True)
    # ### end Alembic commands ###
