"""add deleted check

Revision ID: 5c4a9236460f
Revises: 7a234a0efe27
Create Date: 2019-02-03 09:15:52.525577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c4a9236460f'
down_revision = '7a234a0efe27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reddit_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.String(length=100), nullable=False),
    sa.Column('body', sa.Text(collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('ingested_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('comment_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reddit_comments')
    # ### end Alembic commands ###
