"""add subreddit to summons

Revision ID: 5ca77ffdd9bf
Revises: 39c5bfcfcf92
Create Date: 2019-11-05 00:05:00.599779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ca77ffdd9bf'
down_revision = '39c5bfcfcf92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reddit_bot_summons', sa.Column('subreddit', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reddit_bot_summons', 'subreddit')
    # ### end Alembic commands ###
