"""add meme hash table

Revision ID: 5ec3a1330ae4
Revises: b2b67bea8e6e
Create Date: 2022-07-03 12:31:54.716334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ec3a1330ae4'
down_revision = 'b2b67bea8e6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meme_hash',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.String(length=6), nullable=False),
    sa.Column('hash', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash'),
    sa.UniqueConstraint('post_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meme_hash')
    # ### end Alembic commands ###
