"""Add monitored sub config

Revision ID: 614de12045dc
Revises: bf483a6e5a68
Create Date: 2019-11-17 18:28:50.066345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '614de12045dc'
down_revision = 'bf483a6e5a68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reddit_monitored_sub_config_revision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('revision_id', sa.String(length=36), nullable=False),
    sa.Column('revised_by', sa.String(length=100), nullable=False),
    sa.Column('config', sa.String(length=1000), nullable=False),
    sa.Column('config_loaded_at', sa.DateTime(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.Column('notified', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('revision_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reddit_monitored_sub_config_revision')
    # ### end Alembic commands ###
