"""unique post id image repost

Revision ID: 615326524a9d
Revises: 66cd4de2ba7e
Create Date: 2019-03-01 07:47:36.819231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '615326524a9d'
down_revision = '66cd4de2ba7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'image_reposts', ['post_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_constraint(None, 'image_reposts', type_='unique')
    # ### end Alembic commands ###
