"""new monitor sub fields

Revision ID: 61984e96e62b
Revises: c8d37a241459
Create Date: 2024-02-11 09:12:15.696906

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '61984e96e62b'
down_revision = 'c8d37a241459'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monitored_sub', sa.Column('adult_promoter_removal_reason', sa.String(length=300), nullable=True))
    op.add_column('monitored_sub', sa.Column('adult_promoter_ban_reason', sa.String(length=300), nullable=True))
    op.add_column('monitored_sub', sa.Column('high_volume_reposter_removal_reason', sa.String(length=300), nullable=True))
    op.add_column('monitored_sub', sa.Column('high_volume_reposter_ban_reason', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monitored_sub', 'high_volume_reposter_ban_reason')
    op.drop_column('monitored_sub', 'high_volume_reposter_removal_reason')
    op.drop_column('monitored_sub', 'adult_promoter_ban_reason')
    op.drop_column('monitored_sub', 'adult_promoter_removal_reason')
    # ### end Alembic commands ###
