"""new sub monitor fields

Revision ID: 63a357bd16cc
Revises: b2542fb922a9
Create Date: 2020-03-22 22:06:30.911724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63a357bd16cc'
down_revision = 'b2542fb922a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('reddit_monitored_sub', sa.Column('disable_bot_summons', sa.Boolean(), nullable=True))
    op.add_column('reddit_monitored_sub', sa.Column('disable_summons_after_auto_response', sa.Boolean(), nullable=True))
    op.add_column('reddit_monitored_sub', sa.Column('only_allow_one_summons', sa.Boolean(), nullable=True))
    op.add_column('reddit_monitored_sub', sa.Column('remove_additional_summons', sa.Boolean(), nullable=True))
    op.add_column('reddit_monitored_sub', sa.Column('title_ignore_keywords', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('reddit_monitored_sub', 'title_ignore_keywords')
    op.drop_column('reddit_monitored_sub', 'remove_additional_summons')
    op.drop_column('reddit_monitored_sub', 'only_allow_one_summons')
    op.drop_column('reddit_monitored_sub', 'disable_summons_after_auto_response')
    op.drop_column('reddit_monitored_sub', 'disable_bot_summons')

    # ### end Alembic commands ###
