"""repost count

Revision ID: 66cd4de2ba7e
Revises: 172ec96586e4
Create Date: 2019-02-21 21:24:28.536799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66cd4de2ba7e'
down_revision = '172ec96586e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reddit_post', sa.Column('repost_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('reddit_post', 'repost_count')
    # ### end Alembic commands ###
