"""added is_private

Revision ID: 6a43483a407f
Revises: 150fe2b02cd6
Create Date: 2024-12-14 12:47:11.793717

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6a43483a407f'
down_revision = '150fe2b02cd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.alter_column('subreddit', 'subscribers',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('subreddit', 'nsfw',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subreddit', 'nsfw',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('subreddit', 'subscribers',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
