"""update top reposts

Revision ID: 6e1ac9f20f6e
Revises: 4eb9a001f113
Create Date: 2023-08-02 19:12:13.008812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e1ac9f20f6e'
down_revision = '4eb9a001f113'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stat_top_repost', sa.Column('repost_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stat_top_repost', 'repost_count')
    # ### end Alembic commands ###
