"""add deleted check

Revision ID: 7a234a0efe27
Revises: c7bd0ebfe3d8
Create Date: 2019-02-03 08:36:55.832951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a234a0efe27'
down_revision = 'c7bd0ebfe3d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reddit_post', sa.Column('last_deleted_check', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reddit_post', 'last_deleted_check')
    # ### end Alembic commands ###
