"""Add user report table

Revision ID: 7bd7f8d45d36
Revises: 4db9740d5c18
Create Date: 2020-01-19 18:37:21.098467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bd7f8d45d36'
down_revision = '4db9740d5c18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reddit_user_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.String(length=100), nullable=False),
    sa.Column('reported_by', sa.String(length=100), nullable=False),
    sa.Column('post_type', sa.String(length=15), nullable=True),
    sa.Column('report_type', sa.String(length=10), nullable=False),
    sa.Column('meme_template', sa.Integer(), nullable=True),
    sa.Column('reported_at', sa.DateTime(), nullable=True),
    sa.Column('msg_body', sa.String(length=1000), nullable=True),
    sa.Column('message_id', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reddit_user_report')
    # ### end Alembic commands ###
