"""add subreddit table

Revision ID: 7cba10c4a9b9
Revises: 61984e96e62b
Create Date: 2024-12-08 17:30:04.715160

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7cba10c4a9b9'
down_revision = '61984e96e62b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subreddit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=25), nullable=False),
    sa.Column('subscribers', sa.Integer(), nullable=False),
    sa.Column('nsfw', sa.Boolean(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('bot_banned', sa.Boolean(), nullable=False),
    sa.Column('bot_banned_at', sa.DateTime(), nullable=True),
    sa.Column('last_ban_check', sa.DateTime(), nullable=True),
    sa.Column('last_checked', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_subreddit_name', 'subreddit', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_subreddit_name', table_name='subreddit')
    op.drop_table('subreddit')
    # ### end Alembic commands ###
