"""add sub to config revision

Revision ID: 814f7919c4ff
Revises: 614de12045dc
Create Date: 2019-11-17 20:08:36.186582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '814f7919c4ff'
down_revision = '614de12045dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('reddit_monitored_sub_config_revision', sa.Column('subreddit', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reddit_monitored_sub_config_revision', 'subreddit')

    # ### end Alembic commands ###
