"""add image search table

Revision ID: 87d5bc932e2a
Revises: 814f7919c4ff
Create Date: 2019-11-21 07:13:36.931781

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '87d5bc932e2a'
down_revision = '814f7919c4ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reddit_image_search',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.String(length=100), nullable=False),
    sa.Column('used_historical_index', sa.Boolean(), nullable=False),
    sa.Column('used_current_index', sa.Boolean(), nullable=False),
    sa.Column('target_hamming_distance', sa.Integer(), nullable=False),
    sa.Column('target_annoy_distance', sa.Float(), nullable=False),
    sa.Column('same_sub', sa.Boolean(), nullable=False),
    sa.Column('max_days_old', sa.Integer()),
    sa.Column('filter_dead_matches', sa.Boolean(), nullable=False),
    sa.Column('only_older_matches', sa.Boolean(), nullable=False),
    sa.Column('meme_filter', sa.Boolean(), nullable=False),
    sa.Column('meme_template_Used', sa.Integer(), nullable=True),
    sa.Column('search_time', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id')
    )
    op.drop_table('reddit_reposts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reddit_reposts',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('hamming_distance', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('post_id', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('repost_of', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('detected_at', mysql.DATETIME(), nullable=True),
    sa.Column('post_type', mysql.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('reddit_image_search')
    # ### end Alembic commands ###
