"""add search depth to monitored sub

Revision ID: 881bdeeb6221
Revises: f8eea0f33859
Create Date: 2019-11-03 20:23:04.489130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '881bdeeb6221'
down_revision = 'f8eea0f33859'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reddit_monitored_sub', sa.Column('search_depth', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reddit_monitored_sub', 'search_depth')
    # ### end Alembic commands ###
