"""Add monitored sub table

Revision ID: 88d0c2d9a708
Revises: a973ac81d1db
Create Date: 2019-10-20 14:26:56.504811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88d0c2d9a708'
down_revision = 'a973ac81d1db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reddit_monitored_sub',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('repost_only', sa.Boolean(), nullable=True),
    sa.Column('requestor', sa.String(length=150), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('reddit_post_reply',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.String(length=100), nullable=False),
    sa.Column('reply_id', sa.String(length=100), nullable=True),
    sa.Column('reply_body', sa.String(length=1000, collation='utf8mb4_general_ci'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id'),
    sa.UniqueConstraint('reply_id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reddit_post_reply')
    op.drop_table('reddit_monitored_sub')
    # ### end Alembic commands ###
