"""add bot comment table

Revision ID: 8aa2102f5bf5
Revises: 881bdeeb6221
Create Date: 2019-11-04 23:31:51.317884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8aa2102f5bf5'
down_revision = '881bdeeb6221'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reddit_bot_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.String(length=100), nullable=False),
    sa.Column('comment_body', sa.String(length=2000, collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('perma_link', sa.String(length=1000, collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('comment_left_at', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('subreddit', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reddit_bot_comment')
    # ### end Alembic commands ###
