"""new hash columns

Revision ID: 9145e32428b4
Revises: 66b49444b45d
Create Date: 2019-02-13 12:50:29.748969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9145e32428b4'
down_revision = '66b49444b45d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
