"""change repost stat table

Revision ID: 9557a20ecc84
Revises: 23cfd03f5b32
Create Date: 2023-07-31 19:32:41.864391

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9557a20ecc84'
down_revision = '23cfd03f5b32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stat_top_reposters', sa.Column('post_type_id', mysql.TINYINT(), nullable=True))
    op.add_column('stat_top_reposters', sa.Column('day_range', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'stat_top_reposters', 'post_type', ['post_type_id'], ['id'])
    op.drop_column('stat_top_reposters', 'image_30_day')
    op.drop_column('stat_top_reposters', 'link_7_day')
    op.drop_column('stat_top_reposters', 'link_all')
    op.drop_column('stat_top_reposters', 'image_90_day')
    op.drop_column('stat_top_reposters', 'link_1_day')
    op.drop_column('stat_top_reposters', 'image_1_day')
    op.drop_column('stat_top_reposters', 'link_30_day')
    op.drop_column('stat_top_reposters', 'image_all')
    op.drop_column('stat_top_reposters', 'link_90_day')
    op.drop_column('stat_top_reposters', 'image_7_day')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stat_top_reposters', sa.Column('image_7_day', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('stat_top_reposters', sa.Column('link_90_day', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('stat_top_reposters', sa.Column('image_all', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('stat_top_reposters', sa.Column('link_30_day', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('stat_top_reposters', sa.Column('image_1_day', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('stat_top_reposters', sa.Column('link_1_day', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('stat_top_reposters', sa.Column('image_90_day', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('stat_top_reposters', sa.Column('link_all', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('stat_top_reposters', sa.Column('link_7_day', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('stat_top_reposters', sa.Column('image_30_day', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'stat_top_reposters', type_='foreignkey')
    op.drop_column('stat_top_reposters', 'day_range')
    op.drop_column('stat_top_reposters', 'post_type_id')
    # ### end Alembic commands ###
