"""change repost search

Revision ID: 95cb9bface80
Revises: 4f75d037e368
Create Date: 2023-07-16 13:56:15.953098

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '95cb9bface80'
down_revision = '4f75d037e368'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repost_search', sa.Column('target_title_match', sa.Integer(), nullable=True))
    op.add_column('repost_search', sa.Column('max_matches', sa.Integer(), nullable=True))
    op.add_column('repost_search', sa.Column('same_sub', sa.Boolean(), nullable=True))
    op.add_column('repost_search', sa.Column('max_days_old', sa.Integer(), nullable=True))
    op.add_column('repost_search', sa.Column('filter_dead_matches', sa.Boolean(), nullable=True))
    op.add_column('repost_search', sa.Column('filter_removed_matches', sa.Boolean(), nullable=True))
    op.add_column('repost_search', sa.Column('only_older_matches', sa.Boolean(), nullable=True))
    op.add_column('repost_search', sa.Column('filter_same_author', sa.Boolean(), nullable=True))
    op.add_column('repost_search', sa.Column('filter_crossposts', sa.Boolean(), nullable=True))
    op.add_column('repost_search', sa.Column('target_match_percent', sa.Float(), nullable=True))
    op.add_column('repost_search', sa.Column('target_annoy_distance', sa.Float(), nullable=True))
    op.add_column('repost_search', sa.Column('target_meme_match_percent', sa.Float(), nullable=True))
    op.add_column('repost_search', sa.Column('meme_filter', sa.Boolean(), nullable=True))
    op.add_column('repost_search', sa.Column('max_depth', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'repost_search', 'post_type', ['post_type_id'], ['id'])
    op.drop_column('repost_search', 'search_params')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repost_search', sa.Column('search_params', mysql.VARCHAR(length=1000), nullable=False))
    op.drop_constraint(None, 'repost_search', type_='foreignkey')
    op.drop_column('repost_search', 'max_depth')
    op.drop_column('repost_search', 'meme_filter')
    op.drop_column('repost_search', 'target_meme_match_percent')
    op.drop_column('repost_search', 'target_annoy_distance')
    op.drop_column('repost_search', 'target_match_percent')
    op.drop_column('repost_search', 'filter_crossposts')
    op.drop_column('repost_search', 'filter_same_author')
    op.drop_column('repost_search', 'only_older_matches')
    op.drop_column('repost_search', 'filter_removed_matches')
    op.drop_column('repost_search', 'filter_dead_matches')
    op.drop_column('repost_search', 'max_days_old')
    op.drop_column('repost_search', 'same_sub')
    op.drop_column('repost_search', 'max_matches')
    op.drop_column('repost_search', 'target_title_match')
    # ### end Alembic commands ###
