"""add source to search

Revision ID: 966e14e9c12b
Revises: b2c776dff6e2
Create Date: 2019-12-01 08:09:23.644804

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '966e14e9c12b'
down_revision = 'b2c776dff6e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reddit_image_search', sa.Column('source', sa.String(length=50), nullable=False))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('reddit_image_search', 'source')
    # ### end Alembic commands ###
