"""corsspost parent

Revision ID: 9765922e4a38
Revises: ae0b79c5b71c
Create Date: 2019-01-28 07:44:18.299880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9765922e4a38'
down_revision = 'ae0b79c5b71c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reddit_post', sa.Column('crosspost_parent', sa.String(length=200), nullable=True))
    op.add_column('reddit_post', sa.Column('repost_of', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reddit_post', 'repost_of')
    op.drop_column('reddit_post', 'crosspost_parent')
    # ### end Alembic commands ###
