"""Add new tables

Revision ID: 98bc70df20f0
Revises: 5c4a9236460f
Create Date: 2019-02-10 10:19:56.660561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98bc70df20f0'
down_revision = '5c4a9236460f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reddit_repost_watch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.String(length=100), nullable=False),
    sa.Column('response_type', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_detection', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reddit_reposts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hamming_distance', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.String(length=100), nullable=False),
    sa.Column('repost_of', sa.Integer(), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('reddit_bot_summons', sa.Column('comment_reply_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reddit_bot_summons', 'comment_reply_id')
    op.drop_table('reddit_reposts')
    op.drop_table('reddit_repost_watch')
    # ### end Alembic commands ###
