"""changes

Revision ID: 9ea594b18f1f
Revises: 0a37fbda21ef
Create Date: 2022-07-05 19:01:56.537837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ea594b18f1f'
down_revision = '0a37fbda21ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_comment_left_at', 'bot_comment', ['comment_left_at'], unique=False)
    op.add_column('repost', sa.Column('author', sa.String(length=100), nullable=True))
    op.add_column('repost', sa.Column('post_type', sa.String(length=20), nullable=True))
    op.add_column('repost', sa.Column('subreddit', sa.String(length=100), nullable=False))
    op.create_index('idx_repost_by_type', 'repost', ['post_type', 'detected_at'], unique=False)
    op.create_index('idx_repost_of_date', 'repost', ['detected_at', 'author'], unique=False)
    op.add_column('repost_search', sa.Column('searched_at', sa.DateTime(), nullable=False))
    op.add_column('repost_search', sa.Column('subreddit', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repost_search', 'subreddit')
    op.drop_column('repost_search', 'searched_at')
    op.drop_index('idx_repost_of_date', table_name='repost')
    op.drop_index('idx_repost_by_type', table_name='repost')
    op.drop_column('repost', 'subreddit')
    op.drop_column('repost', 'post_type')
    op.drop_column('repost', 'author')
    op.drop_index('idx_comment_left_at', table_name='bot_comment')
    # ### end Alembic commands ###
