"""add to be deleted

Revision ID: a42b666cd001
Revises: 3c5d92bafc35
Create Date: 2020-05-09 14:18:17.829823

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a42b666cd001'
down_revision = '3c5d92bafc35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('to_be_deleted',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.String(length=100), nullable=False),
    sa.Column('post_type', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('to_be_deleted')
    # ### end Alembic commands ###
