"""left comment field on post

Revision ID: a973ac81d1db
Revises: e5dc3cc2e2f1
Create Date: 2019-10-10 21:22:14.562451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a973ac81d1db'
down_revision = 'e5dc3cc2e2f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reddit_post', sa.Column('left_comment', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reddit_post', 'left_comment')
    # ### end Alembic commands ###
