"""add user ot repost watch

Revision ID: a988fd3d3595
Revises: 98bc70df20f0
Create Date: 2019-02-10 11:53:51.195647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a988fd3d3595'
down_revision = '98bc70df20f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reddit_repost_watch', sa.Column('user', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reddit_repost_watch', 'user')
    # ### end Alembic commands ###
