"""Add summons table

Revision ID: aa64cf52096c
Revises: 433b9dd1d483
Create Date: 2019-01-30 09:42:55.831809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa64cf52096c'
down_revision = '433b9dd1d483'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reddit_bot_summons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.String(length=100), nullable=False),
    sa.Column('comment_id', sa.String(length=100), nullable=True),
    sa.Column('comment_body', sa.String(length=1000), nullable=True),
    sa.Column('comment_reply', sa.String(length=5000), nullable=True),
    sa.Column('summons_received_at', sa.DateTime(), nullable=True),
    sa.Column('summons_replied_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('comment_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reddit_bot_summons')
    # ### end Alembic commands ###
