"""perma link

Revision ID: ae0b79c5b71c
Revises: f3d5af8f5cf7
Create Date: 2019-01-27 21:32:30.309642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae0b79c5b71c'
down_revision = 'f3d5af8f5cf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reddit_post', sa.Column('perma_link', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reddit_post', 'perma_link')
    # ### end Alembic commands ###
