"""add time to search table

Revision ID: b2542fb922a9
Revises: 3b74da7fd47f
Create Date: 2020-03-15 12:14:58.840810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2542fb922a9'
down_revision = '3b74da7fd47f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('reddit_image_search', sa.Column('searched_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('reddit_image_search', 'searched_at')

    # ### end Alembic commands ###
