"""add video hash

Revision ID: b74e53eccb72
Revises: db3722817544
Create Date: 2019-03-06 07:13:20.062417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b74e53eccb72'
down_revision = 'db3722817544'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reddit_video_hashes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('hashes', sa.String(length=1300), nullable=True),
    sa.Column('length', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id')
    )
    op.drop_index('Ingest_rate', table_name='reddit_post')
    op.drop_index('cross_post', table_name='reddit_post')
    op.drop_index('repost_check', table_name='reddit_post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('repost_check', 'reddit_post', ['checked_repost', 'post_type', 'crosspost_parent', 'dhash_h'], unique=False)
    op.create_index('cross_post', 'reddit_post', ['post_type', 'crosspost_checked'], unique=False)
    op.create_index('Ingest_rate', 'reddit_post', ['ingested_at', 'id'], unique=False)
    op.drop_table('reddit_video_hashes')
    # ### end Alembic commands ###
