"""add source to watch

Revision ID: bdd0f81d7ade
Revises: 25b5025a5875
Create Date: 2020-07-26 23:18:37.782028

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bdd0f81d7ade'
down_revision = '25b5025a5875'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('reddit_repost_watch', sa.Column('source', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reddit_repost_watch', 'source')

    # ### end Alembic commands ###
