"""add example column

Revision ID: be81efb9eefa
Revises: d00431f2edcf
Create Date: 2019-10-21 22:48:07.782528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be81efb9eefa'
down_revision = 'd00431f2edcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meme_template', sa.Column('example', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meme_template', 'example')
    # ### end Alembic commands ###
