"""remove unique from image search table

Revision ID: bf14a37474ab
Revises: 966e14e9c12b
Create Date: 2019-12-01 18:51:11.641267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf14a37474ab'
down_revision = '966e14e9c12b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index('post_id', table_name='reddit_image_search')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('post_id', 'reddit_image_search', ['post_id'], unique=True)
    # ### end Alembic commands ###
