"""meme template fields

Revision ID: bf483a6e5a68
Revises: 0842298ca603
Create Date: 2019-11-12 21:02:01.235357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf483a6e5a68'
down_revision = '0842298ca603'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meme_template', sa.Column('approved', sa.Boolean(), nullable=True))
    op.add_column('meme_template', sa.Column('created_from_submission', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meme_template', 'created_from_submission')
    op.drop_column('meme_template', 'approved')
    # ### end Alembic commands ###
