"""check post type id

Revision ID: c483b833921b
Revises: 95cb9bface80
Create Date: 2023-07-16 21:14:35.326805

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c483b833921b'
down_revision = '95cb9bface80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monitored_sub_checked', sa.Column('post_type_id', mysql.TINYINT(), nullable=True))
    op.create_foreign_key(None, 'monitored_sub_checked', 'post_type', ['post_type_id'], ['id'])
    op.drop_column('monitored_sub_checked', 'post_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monitored_sub_checked', sa.Column('post_type', mysql.VARCHAR(length=20), nullable=False))
    op.drop_constraint(None, 'monitored_sub_checked', type_='foreignkey')
    op.drop_column('monitored_sub_checked', 'post_type_id')
    # ### end Alembic commands ###
