"""Add cross_post_checked2

Revision ID: c7bd0ebfe3d8
Revises: 3a1c68487eea
Create Date: 2019-02-02 15:03:25.155302

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c7bd0ebfe3d8'
down_revision = '3a1c68487eea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reddit_post', sa.Column('crosspost_checked', sa.Boolean(), nullable=True))
    op.drop_column('reddit_post', 'cross_post_checked')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reddit_post', sa.Column('cross_post_checked', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('reddit_post', 'crosspost_checked')
    # ### end Alembic commands ###
