"""hihg volume reposter

Revision ID: c8d37a241459
Revises: df91347c3856
Create Date: 2023-09-09 08:36:46.836334

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c8d37a241459'
down_revision = 'df91347c3856'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_whitelist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=25), nullable=False),
    sa.Column('monitored_sub_id', sa.Integer(), nullable=True),
    sa.Column('ignore_adult_promoter_detection', sa.Boolean(), nullable=True),
    sa.Column('ignore_high_volume_repost_detection', sa.Boolean(), nullable=True),
    sa.Column('ignore_repost_detection', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['monitored_sub_id'], ['monitored_sub.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('monitored_sub', sa.Column('adult_promoter_notify_mod_mail', sa.Boolean(), nullable=True))
    op.add_column('monitored_sub', sa.Column('high_volume_reposter_ban_user', sa.Boolean(), nullable=True))
    op.add_column('monitored_sub', sa.Column('high_volume_reposter_remove_post', sa.Boolean(), nullable=True))
    op.add_column('monitored_sub', sa.Column('high_volume_reposter_threshold', sa.Integer(), nullable=True))
    op.add_column('monitored_sub', sa.Column('high_volume_reposter_notify_mod_mail', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('monitored_sub', 'high_volume_reposter_notify_mod_mail')
    op.drop_column('monitored_sub', 'high_volume_reposter_threshold')
    op.drop_column('monitored_sub', 'high_volume_reposter_remove_post')
    op.drop_column('monitored_sub', 'high_volume_reposter_ban_user')
    op.drop_column('monitored_sub', 'adult_promoter_notify_mod_mail')
    op.drop_table('user_whitelist')
    # ### end Alembic commands ###
