"""total bits column

Revision ID: cb4ffe242105
Revises: 1f7d94d90721
Create Date: 2019-02-13 20:45:13.878187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb4ffe242105'
down_revision = '1f7d94d90721'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reddit_post', sa.Column('image_bits_set', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reddit_post', 'image_bits_set')
    # ### end Alembic commands ###
