"""0.1.6 changes

Revision ID: cc31bb26980f
Revises: 63a357bd16cc
Create Date: 2020-04-26 10:07:22.171316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc31bb26980f'
down_revision = '63a357bd16cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('reddit_image_search', sa.Column('index_search_time', sa.Float(), nullable=True))
    op.add_column('reddit_image_search', sa.Column('search_results', sa.Text(length=75000, collation='utf8mb4_general_ci'), nullable=True))
    op.add_column('reddit_image_search', sa.Column('target_title_match', sa.Integer(), nullable=True))
    op.add_column('reddit_image_search', sa.Column('total_filter_time', sa.Float(), nullable=True))
    op.add_column('reddit_monitored_sub', sa.Column('check_all_submissions', sa.Boolean(), nullable=True))
    op.add_column('reddit_monitored_sub', sa.Column('check_title_similarity', sa.Boolean(), nullable=True))
    op.add_column('reddit_monitored_sub', sa.Column('subscribers', sa.Integer(), nullable=True))
    op.add_column('reddit_monitored_sub', sa.Column('target_title_match', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reddit_monitored_sub', 'target_title_match')
    op.drop_column('reddit_monitored_sub', 'subscribers')
    op.drop_column('reddit_monitored_sub', 'check_title_similarity')
    op.drop_column('reddit_monitored_sub', 'check_all_submissions')
    op.drop_column('reddit_image_search', 'total_filter_time')
    op.drop_column('reddit_image_search', 'target_title_match')
    op.drop_column('reddit_image_search', 'search_results')
    op.drop_column('reddit_image_search', 'index_search_time')

    # ### end Alembic commands ###
