"""add created at to image post

Revision ID: cd82a74af6b8
Revises: 22d0da7bc418
Create Date: 2019-11-08 20:11:42.563669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd82a74af6b8'
down_revision = '22d0da7bc418'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reddit_image_post', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reddit_image_post', 'created_at')
    # ### end Alembic commands ###
