"""Add is_private to monitor sub

Revision ID: cf751ec0db2c
Revises: f438cebc0e2e
Create Date: 2021-09-05 22:40:45.347424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf751ec0db2c'
down_revision = 'f438cebc0e2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reddit_monitored_sub', sa.Column('is_private', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reddit_monitored_sub', 'is_private')
    # ### end Alembic commands ###
