"""rename meme template table

Revision ID: d00431f2edcf
Revises: f28c4520b784
Create Date: 2019-10-21 22:28:05.406424

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd00431f2edcf'
down_revision = 'f28c4520b784'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meme_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('dhash_v', sa.String(length=64), nullable=True),
    sa.Column('dhash_h', sa.String(length=64), nullable=True),
    sa.Column('ahash', sa.String(length=64), nullable=True),
    sa.Column('target_hamming', sa.Integer(), nullable=True),
    sa.Column('target_annoy', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('meme_templates')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meme_templates',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('dhash_v', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('dhash_h', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('ahash', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('target_hamming', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('target_annoy', mysql.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('meme_template')
    # ### end Alembic commands ###
