"""date column change

Revision ID: d40f77ce5bd7
Revises: 05166286768a
Create Date: 2023-07-27 20:21:07.979441

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd40f77ce5bd7'
down_revision = '05166286768a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stat_daily_count', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('stat_daily_count', sa.Column('run_at', sa.DateTime(), nullable=True))
    op.drop_index('date', table_name='stat_daily_count')
    op.drop_column('stat_daily_count', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stat_daily_count', sa.Column('date', mysql.VARCHAR(length=10), nullable=False))
    op.create_index('date', 'stat_daily_count', ['date'], unique=False)
    op.drop_column('stat_daily_count', 'run_at')
    op.drop_column('stat_daily_count', 'id')
    # ### end Alembic commands ###
