"""add report msg to sub monitor

Revision ID: d8d293306fa4
Revises: 00c814a44040
Create Date: 2019-10-20 22:24:09.131959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8d293306fa4'
down_revision = '00c814a44040'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reddit_monitored_sub', sa.Column('report_msg', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reddit_monitored_sub', 'report_msg')
    # ### end Alembic commands ###
