"""add meme filter to monitored sub

Revision ID: d92fc4c9f706
Revises: 4de64fd52e67
Create Date: 2019-11-10 19:09:43.842374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd92fc4c9f706'
down_revision = '4de64fd52e67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reddit_monitored_sub', sa.Column('meme_filter', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reddit_monitored_sub', 'meme_filter')
    # ### end Alembic commands ###
