"""Add link hash

Revision ID: da78ebc9b7d0
Revises: a988fd3d3595
Create Date: 2019-02-11 22:46:00.587744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da78ebc9b7d0'
down_revision = 'a988fd3d3595'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reddit_post', sa.Column('url_hash', sa.String(length=32), nullable=True))
    op.drop_index('repost', table_name='reddit_post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('repost', 'reddit_post', ['created_at', 'post_type', 'checked_repost'], unique=False)
    op.drop_column('reddit_post', 'url_hash')
    # ### end Alembic commands ###
