"""remove unused columns

Revision ID: db3722817544
Revises: 31fee8b62426
Create Date: 2019-03-02 20:30:33.686935

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'db3722817544'
down_revision = '31fee8b62426'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reddit_post', sa.Column('selftext', sa.Text(length=75000, collation='utf8mb4_general_ci'), nullable=True))
    op.drop_column('reddit_post', 'dhash_h_set_bits')
    op.drop_column('reddit_post', 'ahash_set_bits')
    op.drop_column('reddit_post', 'images_bits_set')
    op.drop_column('reddit_post', 'repost_of')
    op.drop_column('reddit_post', 'image_bits_set')
    op.drop_column('reddit_post', 'image_hash')
    op.drop_column('reddit_post', 'dhash_v_set_bits')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reddit_post', sa.Column('dhash_v_set_bits', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('reddit_post', sa.Column('image_hash', mysql.VARCHAR(length=64), nullable=True))
    op.add_column('reddit_post', sa.Column('image_bits_set', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('reddit_post', sa.Column('repost_of', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('reddit_post', sa.Column('images_bits_set', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('reddit_post', sa.Column('ahash_set_bits', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('reddit_post', sa.Column('dhash_h_set_bits', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('reddit_post', 'selftext')
    # ### end Alembic commands ###
