"""match percent to image search

Revision ID: dd54702aeb24
Revises: 33870c391f12
Create Date: 2020-08-29 16:46:25.763784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd54702aeb24'
down_revision = '33870c391f12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link_reposts', sa.Column('author', sa.String(length=100), nullable=True))
    op.add_column('reddit_image_search', sa.Column('target_image_match', sa.Integer(), nullable=True))
    op.add_column('reddit_image_search', sa.Column('target_image_meme_match', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reddit_image_search', 'target_image_meme_match')
    op.drop_column('reddit_image_search', 'target_image_match')
    op.drop_column('link_reposts', 'author')

    # ### end Alembic commands ###
