"""remove mod actions

Revision ID: df91347c3856
Revises: 36b522267866
Create Date: 2023-09-03 10:23:06.861499

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'df91347c3856'
down_revision = '36b522267866'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('monitored_sub_mod_action')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('monitored_sub_mod_action',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('action', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('success', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('note', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('monitored_sub_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('post_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['monitored_sub_id'], ['monitored_sub.id'], name='monitored_sub_mod_action_ibfk_1'),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name='monitored_sub_mod_action_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
