"""add template detection hamming

Revision ID: eb7b869ceef6
Revises: be81efb9eefa
Create Date: 2019-10-22 08:27:30.139218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb7b869ceef6'
down_revision = 'be81efb9eefa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meme_template', sa.Column('template_detection_hamming', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meme_template', 'template_detection_hamming')
    # ### end Alembic commands ###
