"""meme hash update

Revision ID: eca6fa2ea7a2
Revises: 5ec3a1330ae4
Create Date: 2022-07-03 12:49:58.549847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eca6fa2ea7a2'
down_revision = '5ec3a1330ae4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('hash', table_name='meme_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('hash', 'meme_hash', ['hash'], unique=True)
    # ### end Alembic commands ###
