"""repostsearch changes

Revision ID: ecb2a06e5575
Revises: b9163bc96a41
Create Date: 2022-07-05 19:21:18.449895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecb2a06e5575'
down_revision = 'b9163bc96a41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repost_search', sa.Column('matches_found', sa.Integer(), nullable=False))
    op.add_column('repost_search', sa.Column('post_type', sa.String(length=20), nullable=True))
    op.add_column('repost_search', sa.Column('search_time', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repost_search', 'search_time')
    op.drop_column('repost_search', 'post_type')
    op.drop_column('repost_search', 'matches_found')
    # ### end Alembic commands ###
