"""Add same sub and expire to repost watch

Revision ID: ee0a870da42b
Revises: bf14a37474ab
Create Date: 2019-12-03 07:20:51.645667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee0a870da42b'
down_revision = 'bf14a37474ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reddit_repost_watch', sa.Column('expire_after', sa.Integer(), nullable=True))
    op.add_column('reddit_repost_watch', sa.Column('same_sub', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reddit_repost_watch', 'same_sub')
    op.drop_column('reddit_repost_watch', 'expire_after')
    # ### end Alembic commands ###
