"""add user review columns

Revision ID: f134f5fecea4
Revises: 550b48e2c922
Create Date: 2023-08-06 17:21:28.783781

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f134f5fecea4'
down_revision = '550b48e2c922'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_review', sa.Column('onlyfans_links_found', sa.Boolean(), nullable=True))
    op.add_column('user_review', sa.Column('fansly_links_found', sa.Boolean(), nullable=True))
    op.add_column('user_review', sa.Column('notes', sa.String(length=100), nullable=True))
    op.drop_column('user_review', 'onlyfans_detected')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_review', sa.Column('onlyfans_detected', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('user_review', 'notes')
    op.drop_column('user_review', 'fansly_links_found')
    op.drop_column('user_review', 'onlyfans_links_found')
    # ### end Alembic commands ###
