"""bad url

Revision ID: f18c7b3b626b
Revises: cb4ffe242105
Create Date: 2019-02-15 08:27:14.988000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f18c7b3b626b'
down_revision = 'cb4ffe242105'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reddit_post', sa.Column('bad_url', sa.Boolean(), nullable=True))
    op.drop_index('ihash', table_name='reddit_post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ihash', 'reddit_post', ['post_type', 'ahash', 'dhash_h', 'dhash_v'], unique=False)
    op.drop_column('reddit_post', 'bad_url')
    # ### end Alembic commands ###
