"""add meme template table

Revision ID: f28c4520b784
Revises: f312952bcdcf
Create Date: 2019-10-21 22:23:32.520855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f28c4520b784'
down_revision = 'f312952bcdcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meme_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('dhash_v', sa.String(length=64), nullable=True),
    sa.Column('dhash_h', sa.String(length=64), nullable=True),
    sa.Column('ahash', sa.String(length=64), nullable=True),
    sa.Column('target_hamming', sa.Integer(), nullable=True),
    sa.Column('target_annoy', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meme_templates')
    # ### end Alembic commands ###
