"""add target hamming and annoy

Revision ID: f312952bcdcf
Revises: d8d293306fa4
Create Date: 2019-10-21 07:30:51.722979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f312952bcdcf'
down_revision = 'd8d293306fa4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reddit_monitored_sub', sa.Column('target_annoy', sa.Float(), nullable=True))
    op.add_column('reddit_monitored_sub', sa.Column('target_hamming', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reddit_monitored_sub', 'target_hamming')
    op.drop_column('reddit_monitored_sub', 'target_annoy')
    # ### end Alembic commands ###
