"""url length

Revision ID: f3d5af8f5cf7
Revises: f8bce0580936
Create Date: 2019-01-27 21:22:20.929331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3d5af8f5cf7'
down_revision = 'f8bce0580936'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
