"""add subreddi to mon sub check

Revision ID: f8eea0f33859
Revises: f1a1e1d9c7fd
Create Date: 2019-11-03 19:34:40.181843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8eea0f33859'
down_revision = 'f1a1e1d9c7fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reddit_monitored_sub_checked', sa.Column('subreddit', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reddit_monitored_sub_checked', 'subreddit')
    # ### end Alembic commands ###
