"""change repost stat table3

Revision ID: fcb87257c621
Revises: 482b71961424
Create Date: 2023-07-31 19:46:46.882494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcb87257c621'
down_revision = '482b71961424'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stat_top_reposters', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_index('author', table_name='stat_top_reposters')
    op.create_index('idx_existing_stat', 'stat_top_reposters', ['author', 'post_type_id', 'day_range'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_existing_stat', table_name='stat_top_reposters')
    op.create_index('author', 'stat_top_reposters', ['author'], unique=False)
    op.drop_column('stat_top_reposters', 'id')
    # ### end Alembic commands ###
