
UNSUPPORTED_POST_TYPE = 'Sorry, I don\'t support this post type right now.  Feel free to check back in the future!'
REPOST_ALL = '**Times Seen:** {occurrences} \n\n**Total Searched:** {search_total}\n\n**First Saw:** [{original_href}]({original_link})\n\nHere are all the instances I\'ve seen:\n\n'
REPOST_NO_RESULT = 'I\'ve seen {total} posts but have never seen this one. \n\n'
LINK_ALL = 'I have seen this link {occurrences} times\n\n**Total Searched:** {searched}\n\n**Oldest Post:** [{original_href}]({link_text})'
WATCH_ENABLED = 'I will now watch for matching posts.\n\nIf someone posts this same content I will let you know via {response}'
WATCH_DISABLED = 'I have removed your repost watch from this post'
WATCH_NOT_FOUND = 'I was not able to locate an existing repost watch for this post'
WATCH_DUPLICATE = 'You already have a watch setup for this post'
UNKNOWN_COMMAND = 'I don\'t understand your command. You can use \'!repost commands\' to see a list of commands I understand'
STATS = '**Total Posts indexed:** {post_count}\n\n**Image Posts:** {images}\n\n**Link Posts:** {links}\n\n**Video Posts:** {video}\n\n **Text Posts:** {text}\n\n **Oldest Post:** {oldest}\n\n**Reposts Found:** {reposts}\n\n**Times Summoned:** {summoned}'
SIGNATURE = 'Wiki | About Me | [Report a Bug](https://www.reddit.com/message/compose/?to=RepostSleuthBot&subject=RepostSleuthBot%20Bug)'